# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_data": "01_linear_regression.ipynb",
         "make_point_plot": "01_linear_regression.ipynb",
         "make_line_plot": "01_linear_regression.ipynb",
         "gradient_descent": "01_linear_regression.ipynb"}

modules = ["linear_regression.py"]

doc_url = "https://sci2lab.github.io/ml_tutorial/"

git_url = "https://github.com/sci2lab/ml_tutorial/tree/master/"

def custom_doc_links(name): return None
