# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"flip_coin": "01_mle_map.ipynb",
         "read_dir": "02_naive_bayes.ipynb",
         "load_data": "10_bert_farsi_sentiment.ipynb",
         "train": "04_logistic_regression.ipynb",
         "test": "02_naive_bayes.ipynb",
         "run": "02_naive_bayes.ipynb",
         "generate_data": "09_rnn.ipynb",
         "make_point_plot": "03_linear_regression.ipynb",
         "make_line_plot": "03_linear_regression.ipynb",
         "gradient_descent": "03_linear_regression.ipynb",
         "plot_data": "04_logistic_regression.ipynb",
         "sigmoid": "04_logistic_regression.ipynb",
         "predict": "04_logistic_regression.ipynb",
         "decision_boundary": "04_logistic_regression.ipynb",
         "classify": "04_logistic_regression.ipynb",
         "cost_function": "04_logistic_regression.ipynb",
         "update_weights": "04_logistic_regression.ipynb",
         "get_accuracy": "04_logistic_regression.ipynb",
         "NeuralNetwork": "05_neural_network.ipynb",
         "get_num_lines": "06_cnn.ipynb",
         "load_symbols": "06_cnn.ipynb",
         "get_pixel": "07_autoencoder.ipynb",
         "change_image_background": "07_autoencoder.ipynb",
         "create_augmentor_pipeline": "07_autoencoder.ipynb",
         "preprocess": "08_tfidf.ipynb",
         "create_tfidf_features": "08_tfidf.ipynb",
         "calculate_similarity": "08_tfidf.ipynb",
         "show_similar_documents": "08_tfidf.ipynb",
         "create_index": "08_tfidf.ipynb",
         "index_data": "08_tfidf.ipynb",
         "index_batch": "08_tfidf.ipynb",
         "run_query_loop": "08_tfidf.ipynb",
         "handle_query": "08_tfidf.ipynb",
         "encode": "09_rnn.ipynb",
         "decode": "09_rnn.ipynb",
         "file_name": "10_bert_farsi_sentiment.ipynb",
         "df": "10_bert_farsi_sentiment.ipynb",
         "create_small_dataset": "10_bert_farsi_sentiment.ipynb",
         "remove_emoji": "10_bert_farsi_sentiment.ipynb",
         "convert_data_into_input_example": "10_bert_farsi_sentiment.ipynb",
         "my_solution": "10_bert_farsi_sentiment.ipynb",
         "example_to_features": "10_bert_farsi_sentiment.ipynb",
         "plot_history": "10_bert_farsi_sentiment.ipynb",
         "example_to_features_predict": "10_bert_farsi_sentiment.ipynb",
         "get_prediction": "10_bert_farsi_sentiment.ipynb"}

modules = ["mle_map.py",
           "naive_bayes.py",
           "linear_regression.py",
           "logistic_regression.py",
           "neural_network.py",
           "cnn.py",
           "autoencoder.py",
           "tfidf.py",
           "rnn.py",
           "bert_farsi.py"]

doc_url = "https://sci2lab.github.io/ml_tutorial/"

git_url = "https://github.com/sci2lab/ml_tutorial/tree/master/"

def custom_doc_links(name): return None
