# AUTOGENERATED! DO NOT EDIT! File to edit: 01_mle_map.ipynb (unless otherwise specified).

__all__ = ['flip_coin']

# Cell
import altair as alt
import numpy as np
import pandas as pd
from scipy.stats import norm

def flip_coin(num_of_experiments = 1000, num_of_flips = 30):
    """
    Flip the coin `num_of_flips` times and repeat this experiment `num_of_experiments` times. And
    return the number of heads grouped together in all the experiments.
    """
    all_heads = []
    for i in range(num_of_experiments):
        heads = tails = 0
        for counter in range(num_of_flips):
            num = np.random.randint(0,2)
            if num == 0:
                heads += 1
            else:
                tails += 1
        all_heads.append(heads)

    # group the number of heads in all the experiments
    flip_heads = []
    for flip in range(num_of_flips + 1):
        num_of_heads = 0
        for h in all_heads:
            if h == flip:
                num_of_heads += 1
        flip_heads.append(num_of_heads)
    return flip_heads