# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_data": "00_core.ipynb",
         "gradient_descent": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://sci2lab.github.io/linear_regression/"

git_url = "https://github.com/sci2lab/linear_regression/tree/master/"

def custom_doc_links(name): return None
