# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['generate_data']

# Cell
import numpy as np
import pandas as pd
import altair as altair
def generate_data():
    """It generates dummy data."""
    noise = np.random.randn(100,1)
    X = 2 * np.random.rand(100,1)
    y = 5 + 3 * X + noise
    return X,y